# ─── Base de Datos MySQL ──────────────────────────────────────────
spring.datasource.url=jdbc:mysql://localhost:3306/mi_optica?useSSL=false&serverTimezone=America/Guatemala&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ─── JPA / Hibernate ──────────────────────────────────────────────
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# ─── DESHABILITAR schema.sql automático ───────────────────────────
spring.sql.init.mode=never

# ─── Thymeleaf ────────────────────────────────────────────────────
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.mode=HTML

# ─── Servidor ─────────────────────────────────────────────────────
server.port=8080
server.servlet.context-path=/

# ─── Sesiones ─────────────────────────────────────────────────────
spring.session.timeout=30m

# ─── Mensajes de error ────────────────────────────────────────────
server.error.include-message=always
server.error.include-binding-errors=always

# ─── Nombre de la aplicación ──────────────────────────────────────
spring.application.name=mi-optica
# ─── Subida de archivos (foto de perfil) ──────────────────────────
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB